name: local_chat_server
description: Local chat server
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  shelf_static: ^1.1.2
  watcher: ^1.1.0
  uuid: ^4.3.3
  path: ^1.9.0
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.0
